### ISSUE TITLE
Example Config for S3 sink

### ISSUE THREAD

**Issue by tanujd11** [heptio/eventrouter#123]
Hey, I was looking at this project looks cool. Can I get an example of config.json for S3 as it will be very helpful. Thanks

**Comment by alok87** [comment]
```yaml
apiVersion: v1
data:
  config.json: |-
    {
        "sink": "s3sink",
        "s3SinkAccessKeyID": "sample",
        "s3SinkSecretAccessKey": "sample",
        "s3SinkRegion": "ap-south-1",
        "s3SinkBucket": "bucket",
        "s3SinkBucketDir": "events",
        "s3SinkBufferSize": 1500,
        "s3SinkDiscardMessages": true,
        "s3SinkOutputFormat": "flatjson",
        "s3SinkUploadInterval": 120
    }
kind: ConfigMap
metadata:
  name: eventrouter-cm
  namespace: kube-system
```

I am using this.
